<MainScreen>:
    CustomBox:
        id: layout
        size: root.size


<CustomBox@BoxLayout>:
    MyTextInput:
        id: id1
        focus: True
        focused: "id1"
    MyTextInput:
        id: id2
        focused: "id2"
    MyTextInput:
        id: id3
        focused: "id3"
    MyTextInput:
        id: id4
        focused: "id4"
    MyTextInput:
        id: id5
        focused: "id5"